name: virtual_zen
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  flutter_screenutil: ^5.9.3
  another_flushbar: ^1.12.30
  provider: ^6.1.2
  email_validator: ^3.0.0
  flutter_svg: ^2.0.17
  google_sign_in: ^6.2.2
  fluttertoast: ^8.2.12
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.7
  youtube_player_flutter: ^9.1.1
  intl: ^0.20.2
  firebase_database: ^11.3.5
  emoji_picker_flutter: ^4.3.0
  cloud_functions: ^5.5.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  firebase_messaging: ^15.2.5
  app_settings: ^6.1.1
  flutter_local_notifications: ^19.1.0
  image_picker: ^1.1.2
  dio: ^5.8.0+1
  photo_view: ^0.15.0
  gallery_saver_plus: ^3.2.8
  permission_handler: ^12.0.0+1
  video_player: ^2.10.0
  chewie: ^1.11.3
  youtube_explode_dart: ^2.4.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_icon.png"
  adaptive_icon_foreground: "assets/logo/logo_foreground.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/videos/
    - assets/firebase_service_account.json

  fonts:
    - family: Esteban
      fonts:
        - asset: assets/fonts/Esteban-Regular.ttf

