// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ6GrQjvtuJYeQodKWZ1Ia7IXYiwZvnxs',
    appId: '1:705365726490:android:c3df069d6bfffdcdfbc8a3',
    messagingSenderId: '705365726490',
    projectId: 'virtualzenapp',
    storageBucket: 'virtualzenapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-CIJ81U9mt3Aw3DaB6poRXh_2PSwOJDc',
    appId: '1:705365726490:ios:0c1375dd62549cf0fbc8a3',
    messagingSenderId: '705365726490',
    projectId: 'virtualzenapp',
    storageBucket: 'virtualzenapp.firebasestorage.app',
    iosClientId: '705365726490-b7k2c2l6pokbi53e8nuoitepdkqb8ouu.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtualZen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-CIJ81U9mt3Aw3DaB6poRXh_2PSwOJDc',
    appId: '1:705365726490:ios:0c1375dd62549cf0fbc8a3',
    messagingSenderId: '705365726490',
    projectId: 'virtualzenapp',
    storageBucket: 'virtualzenapp.firebasestorage.app',
    iosClientId: '705365726490-b7k2c2l6pokbi53e8nuoitepdkqb8ouu.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtualZen',
  );
}
